name: Tests + Allure report


on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  test-and-allure:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest


      - name: Run tests (generate Allure results)
        run: |
          pytest -q test_echo.py --alluredir=allure-results


      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.9
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages


      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report


  deploy:
    needs: test-and-allure
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}


    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
